// Code generated by the klever-sc build system. DO NOT EDIT.
////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           12
// Total number of exported functions:  14

#![no_std]

klever_sc_wasm_adapter::allocator!();
klever_sc_wasm_adapter::panic_handler!();

klever_sc_wasm_adapter::endpoints! {
    token_factory
    (
        init => init
        upgrade => upgrade
        issue => issue
        mintToken => mint_token
        burnToken => burn_token
        transferTokenOwnership => transfer_token_ownership
        changeContractName => change_contract_name
        pause => pause
        unpause => unpause
        isPaused => is_paused
        getTotalIssued => get_total_issued
        getTokensByCreator => get_tokens_by_creator
        getCreatorTokenCount => get_creator_token_count
        getTokenCreator => get_token_creator
    )
}
