import 'dotenv/config'
import { z } from 'zod'

/**
 * Backend configuration.
 *
 * The wallet PEM file is optional: without it the server starts in
 * read-only mode (all contract views work, the write endpoints
 * respond 503).
 */
const schema = z.object({
  PORT: z.coerce.number().int().positive().default(3000),
  /**
   * Listen interface. Defaults to loopback: the server signs transactions with
   * the wallet and has no authentication, so it must not be exposed to the network.
   */
  HOST: z.string().default('127.0.0.1'),

  /** Klever network: mainnet | testnet | devnet | local */
  KLEVER_NETWORK: z.enum(['mainnet', 'testnet', 'devnet', 'local']).default('testnet'),
  /** Custom node URL (overrides KLEVER_NETWORK when set) */
  KLEVER_NODE_URL: z.string().url().optional(),
  /** Custom API URL (used together with KLEVER_NODE_URL) */
  KLEVER_API_URL: z.string().url().optional(),
  /** Chain ID required when using custom URLs */
  KLEVER_CHAIN_ID: z.string().optional(),

  /** bech32 address of the already deployed TokenFactory */
  CONTRACT_ADDRESS: z
    .string()
    .regex(/^klv1[0-9a-z]{38,}$/, 'CONTRACT_ADDRESS must be a valid klv1 address')
    .optional(),

  /** Path to the PEM file (Klever format) of the account that signs transactions */
  WALLET_PEM_PATH: z.string().optional(),
  /** PEM password, only when the file was generated encrypted */
  WALLET_PEM_PASSWORD: z.string().optional(),

  /** Path to the ABI generated by the contract build */
  ABI_PATH: z.string().default('../token-factory/output/token-factory.abi.json'),
  /** Path to the wasm, used only by the deploy script */
  WASM_PATH: z.string().default('../token-factory/output/token-factory.wasm'),

  /** Wait for on-chain confirmation by default on the write endpoints */
  WAIT_FOR_TX: z
    .enum(['true', 'false'])
    .default('true')
    .transform((v) => v === 'true'),
})

/** Empty variables in .env (`FOO=`) count as unset. */
const env = Object.fromEntries(
  Object.entries(process.env).filter(([, value]) => value !== undefined && value !== ''),
)

const parsed = schema.safeParse(env)

if (!parsed.success) {
  const issues = parsed.error.issues.map((i) => `  - ${i.path.join('.')}: ${i.message}`).join('\n')
  throw new Error(`Invalid configuration (.env):\n${issues}`)
}

export const config = parsed.data

/** Read-only mode: without the wallet PEM there is no way to sign transactions. */
export const canSign = Boolean(config.WALLET_PEM_PATH)
