import { readFileSync } from "node:fs";

import { loadPrivateKeyFromPemFile } from "@klever/connect-crypto";
import {
  Contract,
  KleverProvider,
  NodeWallet,
  createCustomNetwork,
  type ContractABI,
  type Network,
} from "@klever/connect";

import { canSign, config } from "./config.js";
import { unavailable } from "./lib/errors.js";
import { fromPackageRoot } from "./lib/paths.js";

export interface KleverContext {
  provider: KleverProvider;
  network: Network;
  /** Absent when the server runs in read-only mode. */
  wallet?: NodeWallet;
  abi: ContractABI;
  /**
   * TokenFactory instance (with a signer when there is a wallet, provider only otherwise).
   * Absent until the contract is configured: via CONTRACT_ADDRESS in
   * .env or via the deploy done on the page (`POST /api/contract/deploy`).
   */
  contract?: Contract;
  contractAddress?: string;
}

let context: KleverContext | undefined;

/** Reads the ABI generated by the contract build (`output/token-factory.abi.json`). */
export function loadContractAbi(): ContractABI {
  const path = fromPackageRoot(config.ABI_PATH);
  try {
    return JSON.parse(readFileSync(path, "utf8")) as ContractABI;
  } catch (err) {
    throw new Error(
      `Could not read the ABI at ${path}. Run the contract build (\`~/klever-sdk/ksc all build\`) or adjust ABI_PATH. Cause: ${
        err instanceof Error ? err.message : String(err)
      }`,
    );
  }
}

/** Builds the network from .env: known name or custom URLs. */
export function resolveNetwork():
  Network | "mainnet" | "testnet" | "devnet" | "local" {
  if (config.KLEVER_NODE_URL) {
    if (!config.KLEVER_CHAIN_ID) {
      throw new Error(
        "KLEVER_CHAIN_ID is required when KLEVER_NODE_URL is set",
      );
    }
    return createCustomNetwork({
      chainId: config.KLEVER_CHAIN_ID,
      node: config.KLEVER_NODE_URL,
      api: config.KLEVER_API_URL ?? config.KLEVER_NODE_URL,
      isTestnet: config.KLEVER_CHAIN_ID !== "108",
    });
  }
  return config.KLEVER_NETWORK;
}

export function createProvider(): KleverProvider {
  return new KleverProvider({ network: resolveNetwork() });
}

/**
 * Creates and connects the wallet that signs transactions from the PEM at WALLET_PEM_PATH.
 *
 * The klever-connect loader checks that the private key derives the address in the
 * PEM header; `connect()` only derives the public key and address locally —
 * neither makes a network call.
 */
export async function createWallet(
  provider: KleverProvider,
): Promise<NodeWallet> {
  if (!config.WALLET_PEM_PATH) {
    throw new Error("WALLET_PEM_PATH not configured");
  }
  const pemPath = fromPackageRoot(config.WALLET_PEM_PATH);
  let privateKey: Uint8Array;
  try {
    ({ privateKey } = await loadPrivateKeyFromPemFile(pemPath, {
      ...(config.WALLET_PEM_PASSWORD
        ? { password: config.WALLET_PEM_PASSWORD }
        : {}),
    }));
  } catch (err) {
    throw new Error(
      `Could not load the wallet at ${pemPath}. Generate one with \`npm run wallet:new\` or adjust WALLET_PEM_PATH. Cause: ${
        err instanceof Error ? err.message : String(err)
      }`,
    );
  }
  const wallet = new NodeWallet(
    provider,
    Buffer.from(privateKey).toString("hex"),
  );
  await wallet.connect();
  return wallet;
}

/**
 * Initializes provider + wallet + contract instance once.
 *
 * The klever-connect `Contract` takes the signer; it reuses the provider of the
 * wallet, so queries (readonly) and invokes (transaction) go through the same instance.
 *
 * Without CONTRACT_ADDRESS the server still starts, in "not configured" mode:
 * only `/api/contract` and `/api/contract/deploy` respond until the deploy happens.
 */
export async function initKlever(): Promise<KleverContext> {
  if (context) return context;

  const provider = createProvider();
  const abi = loadContractAbi();
  const wallet = canSign ? await createWallet(provider) : undefined;

  context = {
    provider,
    network: provider.network,
    ...(wallet ? { wallet } : {}),
    abi,
  };

  if (config.CONTRACT_ADDRESS) setContractAddress(config.CONTRACT_ADDRESS);

  return context;
}

/** Points the backend at a TokenFactory (at boot, via .env, or right after the deploy). */
export function setContractAddress(address: string): Contract {
  const ctx = getKlever();
  const contract = new Contract(address, ctx.abi, ctx.wallet ?? ctx.provider);
  ctx.contract = contract;
  ctx.contractAddress = address;
  return contract;
}

export function getKlever(): KleverContext {
  if (!context)
    throw new Error("Klever not initialized — call initKlever() first");
  return context;
}

/** Context with the contract guaranteed; 503 when no TokenFactory is configured yet. */
export function requireContract(): KleverContext & {
  contract: Contract;
  contractAddress: string;
} {
  const ctx = getKlever();
  if (!ctx.contract || !ctx.contractAddress) {
    throw unavailable(
      "Contract not configured: deploy from the page or set CONTRACT_ADDRESS in .env",
    );
  }
  return ctx as KleverContext & { contract: Contract; contractAddress: string };
}
